travis:
  secure:
    BINSTAR_TOKEN: vGKqWc/SyPzoHAJbCHHRJNZnZ79uHkYcrPclGor6UT4W1vrV0MshUGhYbsAuLwLDVl/LQCcfAXRfb0+rXlE92Wt0UYzK9sUUeVSqDB0Yqso7wdRq1W4X+4K55fzNuWJtgj/5EL14ViYnOMKpuQXhdb5wYP44Qy1R+50Xj2vCse4vBlrCD/jIMagKTM565cKkprHsW+VGAPMqFWa7r0NFCf3nL0UCSmescDGkKxkQJHFrOqbL+72nvmDmdDYxTYQlqJL4CfmD+BhZQSfE7Jfh54bV3L3erbwAQFxvrNGm0e07/zGSpXAna/MFmwh05aRRQiAevVPObnC0sYHbtz/GrzshumwTdwlS22cFfs5M9dm2mY6W7KGJ+V4gPHN7U9A+Ek8CfTZL5qBjOIxv9fAEsbt17jBgbgpdkLYWA2GLBT4R+2Yu8xpGpyGzkZrB8gQrHpKxrtqwV3ta6cM7DxuSvpZUkMHtvxfqia4pnieQW4IfSTKyrtiAbRFBf6dmdM/F1oqZ33xLFJadRpYZKVI85uxohsgxGE5FJ1H9wSCF3ZgcoJKxP1HdBIUaF2ZYu4UKWA/juIjVd8QjdKw4L2xUnRZahGlczgy0k9wi+RybmUDF3RiWNy08iOsB7XIWcKI8Zvr9rq51t0+OR850GnWtpsHdFN9WjmMqT0AeyJ+Ze8s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
