travis:
  secure:
    BINSTAR_TOKEN: MhpzhJUZhxN/Z08NZVxGa9i5amUAzij2RRnTqXWIp3B/bJKriWUSIwyW1xlHd2AEFm18mptkDFQF5XrNvTqn+G+vTqZB3IPVzEsI7wgc1yO1VrefpRO3z/l59s7L2Qhj8QOc0cRW/3ZS+wreHhAHQ9nJ4A2k9BtshbeP6WD9jvuoW5qJdsu3EdIWLvhNHMwc9Hpu9COFMBnot4DwmguPFskATePpwXyC9SFQtDINTeNWzqhRF7pLym1r47Dg2eqqMrpjm2Po4E5CC0Bz+APdtetBLPHrphfsXlNrPpLXSeHl9liYrDfkNyCmY/M7bcYB/vREok7VO8ydH/mna4vuRllzddzyD6V2T9ek9iKH9zPDH9Xn2cDFeDTw6842d9pDUoqUo0lv4LJXgk0zMn/ThSZ6KBzWnXXhyDJ9k/yk8eZ7aNovsCHqYyp0u/hYUoJrtJXhY3Tc3+tDHxrn5vcn7eXEcTDXe6HO7usbJrT7NVc5EDOMPKeuDSAP0Bvfc7lQbrU0rosK4qVWAdf+ervNB4LfUWpWzPKUENwxP1xPVmVI4JEF7wQCfLrFZurQffRiJhDwYidgjZUnsg1FIv3CGg3FCUXMu0pCilSHyhD8xPAcpQcH5wByGyO3KOt9JpEHBHPUhdYHlRm6x50LBO29BVY7b4nFOFjAG85l5tzJyV8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
